//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabio_Aplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTO_INSUMOS
    {
        public int ID { get; set; }
        public string TIPO { get; set; }
        public int VALOR { get; set; }
        public string OBS { get; set; }
        public string ESPECIFICACAO_TIPO { get; set; }
    }
}
