//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabio_Aplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUNCIONARIOS()
        {
            this.PAGAMENTO_FUNCIONARIOS = new HashSet<PAGAMENTO_FUNCIONARIOS>();
        }
    
        public int ID { get; set; }
        public string NOME { get; set; }
        public Nullable<int> SALARIO { get; set; }
        public Nullable<System.DateTime> DATACAD { get; set; }
        public Nullable<System.DateTime> DATAALT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGAMENTO_FUNCIONARIOS> PAGAMENTO_FUNCIONARIOS { get; set; }
    }
}
