//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabio_Aplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BancoEntities : DbContext
    {
        public BancoEntities()
            : base("name=BancoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AQUISICAO_ANIMAIS> AQUISICAO_ANIMAIS { get; set; }
        public virtual DbSet<CUSTO_INSUMOS> CUSTO_INSUMOS { get; set; }
        public virtual DbSet<CUSTOS_OUTROS> CUSTOS_OUTROS { get; set; }
        public virtual DbSet<FUNCIONARIOS> FUNCIONARIOS { get; set; }
        public virtual DbSet<MANUTENCAO_MAQUINAS> MANUTENCAO_MAQUINAS { get; set; }
        public virtual DbSet<PAGAMENTO_FUNCIONARIOS> PAGAMENTO_FUNCIONARIOS { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
