//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabio_Aplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGAMENTO_FUNCIONARIOS
    {
        public int ID { get; set; }
        public int FUNCIONARIO_ID { get; set; }
        public System.DateTime DATA_PAGAMENTO { get; set; }
        public int SALARIO { get; set; }
        public int DESCONTO { get; set; }
        public int ACRESCIMO { get; set; }
        public string OBS { get; set; }
    
        public virtual FUNCIONARIOS FUNCIONARIOS { get; set; }
    }
}
