//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabio_Aplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID { get; set; }
        public string NOME { get; set; }
        public string SENHA { get; set; }
        public System.DateTime DATACAD { get; set; }
        public System.DateTime DATAALT { get; set; }
        public bool ATIVO { get; set; }
    }
}
